All:
	@echo "----------Building project:[ goopal - Debug ]----------"
	@"$(MAKE)" -f  "goopal.mk"
clean:
	@echo "----------Cleaning project:[ goopal - Debug ]----------"
	@"$(MAKE)" -f  "goopal.mk" clean
.PHONY: clean All

